package comp3350.wwsys.tests.business;

import comp3350.wwsys.business.EntryValidator;
import comp3350.wwsys.objects.Entry;
import comp3350.wwsys.business.EntryValidationException;

import java.time.LocalDateTime;
import java.util.UUID;

import static org.junit.Assert.assertThrows;



import org.junit.Before;
import org.junit.Test;


/**
 * Unit tests for the {@code EntryValidator} class.
 * Ensures validation of entry attributes such as description, category, and amount.
 */
public class EntryValidatorTest {

    Entry entryOne;

    @Before
    public void setUp() {
        entryOne = new Entry(UUID.randomUUID(),99,"hello","allowance","income", LocalDateTime.now());

    }

    /**
     * Tests the validation of an entry's description.
     * Ensures that a description exceeding the allowed length is handled correctly.
     */
    @Test
    public void validateEffectiveDateTest() {
        entryOne = new Entry(null,99,"hello","Allowance","Income", null);
        assertThrows(EntryValidationException.class,() ->EntryValidator.validateEntry(entryOne));

        entryOne = new Entry(null,99,"hello","Allowance","Income", LocalDateTime.now());
        assertThrows(EntryValidationException.class,() ->EntryValidator.validateEntry(entryOne));
    }

    @Test
    public void validateUserIdTest() {
        entryOne = new Entry(UUID.randomUUID() ,null,99,"hello","allowance","Income", LocalDateTime.now(),LocalDateTime.now());
        assertThrows(EntryValidationException.class,() ->EntryValidator.validateEntry(entryOne));

    }

    /**
     * Tests the validation of an entry's category.
     * Ensures that an empty category string is not allowed.
     */
    @Test
    public void validateCategoryTest() {
        entryOne = new Entry(UUID.randomUUID() ,null,99,"hello","allowance","", LocalDateTime.now(),LocalDateTime.now());
        assertThrows(EntryValidationException.class,() ->EntryValidator.validateEntry(entryOne));

    }

    /**
     * Tests the validation of an entry's Description.
     */
    @Test
    public void validateDescriptionTest() {
        entryOne = new Entry(UUID.randomUUID() ,null,99,null,"allowance","", LocalDateTime.now(),LocalDateTime.now());
        assertThrows(EntryValidationException.class,() ->EntryValidator.validateEntry(entryOne));

        String desciption = "akjfhaifhauifhauiakjfhaifhauifhauifhaiuhfiushfiushifhkkdsjhgdfksjhgkdjshgkjlsdfhgkjdsfhgjkfdhgkjhsdkljfhgkjdfshgkjdshgkjhfdjkhgjkdhgjfkhgdfkgfdsffffffsdkjhfishtiouasghtfuerbghufgueihbgfiughufgthuyhgkjhgfdjkhgjkdfhkjghdjkghdkjhgkjdhgkdhfjkdhgjkdfhgdjkhgjkdgfhjkdfhgjkhfgkhdgjkhgjkdfhgkjdhgkdhgkjdhgkjdhgjkdhgksuifhseiuhfisuhfiushfiushfiuhsfiuhesiufhsuihfiueshfiueshfuihsifuhseiuhfiushfiushfiushfiushfiushfiushfiuhsiufhsiufhsiufhsiuhfsiuhfiushfiushfiuhfsiuhfiuhfsiufhiusfhisuhfiushfiuhfikjdshlijuhsdiughtfuishgiofhgjikdhgiudhiugdehgiueegiueguihgiuehgiuhiueghgiuhegiuheiuhgiuehgiuehgiuehgiuhgiuehgiuehgiuehghuakjfhaifhauifhauifhaiuhfiushfiushifhkkdsjhgdfksjhgkdjshgkjlsdfhgkjdsfhgjkfdhgkjhsdkljfhgkjdfshgkjdshgkjhfdjkhgjkdhgjfkhgdfkgfdsffffffsdkjhfishtiouasghtfuerbghufgueihbgfiughufgthuyhgkjhgfdjkhgjkdfhkjghdjkghdkjhgkjdhgkdhfjkdhgjkdfhgdjkhgjkdgfhjkdfhgjkhfgkhdgjkhgjkdfhgkjdhgkdhgkjdhgkjdhgjkdhgksuifhseiuhfisuhfiushfiushfiuhsfiuhesiufhsuihfiueshfiueshfuihsifuhseiuhfiushfiushfiushfiushfiushfiushfiuhsiufhsiufhsiufhsiuhfsiuhfiushfiushfiuhfsiuhfiuhfsiufhiusfhisuhfiushfiuhfikjdshlijuhsdiughtfuishgiofhgjikdhgiudhiugdehgiueegiueguihgiuehgiuhiueghgiuhegiuheiuhgiuehgiuehgiuehgiuhgiuehgiuehgiuehghuakjfhaifhauifhauifhaiuhfiushfiushifhkkdsjhgdfksjhgkdjshgkjlsdfhgkjdsfhgjkfdhgkjhsdkljfhgkjdfshgkjdshgkjhfdjkhgjkdhgjfkhgdfkgfdsffffffsdkjhfishtiouasghtfuerbghufgueihbgfiughufgthuyhgkjhgfdjkhgjkdfhkjghdjkghdkjhgkjdhgkdhfjkdhgjkdfhgdjkhgjkdgfhjkdfhgjkhfgkhdgjkhgjkdfhgkjdhgkdhgkjdhgkjdhgjkdhgksuifhseiuhfisuhfiushfiushfiuhsfiuhesiufhsuihfiueshfiueshfuihsifuhseiuhfiushfiushfiushfiushfiushfiushfiuhsiufhsiufhsiufhsiuhfsiuhfiushfiushfiuhfsiuhfiuhfsiufhiusfhisuhfiushfiuhfikjdshlijuhsdiughtfuishgiofhgjikdhgiudhiugdehgiueegiueguihgiuehgiuhiueghgiuhegiuheiuhgiuehgiuehgiuehgiuhgiuehgiuehgiuehghuakjfhaifhauifhauifhaiuhfiushfiushifhkkdsjhgdfksjhgkdjshgkjlsdfhgkjdsfhgjkfdhgkjhsdkljfhgkjdfshgkjdshgkjhfdjkhgjkdhgjfkhgdfkgfdsffffffsdkjhfishtiouasghtfuerbghufgueihbgfiughufgthuyhgkjhgfdjkhgjkdfhkjghdjkghdkjhgkjdhgkdhfjkdhgjkdfhgdjkhgjkdgfhjkdfhgjkhfgkhdgjkhgjkdfhgkjdhgkdhgkjdhgkjdhgjkdhgksuifhseiuhfisuhfiushfiushfiuhsfiuhesiufhsuihfiueshfiueshfuihsifuhseiuhfiushfiushfiushfiushfiushfiushfiuhsiufhsiufhsiufhsiuhfsiuhfiushfiushfiuhfsiuhfiuhfsiufhiusfhisuhfiushfiuhfikjdshlijuhsdiughtfuishgiofhgjikdhgiudhiugdehgiueegiueguihgiuehgiuhiueghgiuhegiuheiuhgiuehgiuehgiuehgiuhgiuehgiuehgiuehghuakjfhaifhauifhauifhaiuhfiushfiushifhkkdsjhgdfksjhgkdjshgkjlsdfhgkjdsfhgjkfdhgkjhsdkljfhgkjdfshgkjdshgkjhfdjkhgjkdhgjfkhgdfkgfdsffffffsdkjhfishtiouasghtfuerbghufgueihbgfiughufgthuyhgkjhgfdjkhgjkdfhkjghdjkghdkjhgkjdhgkdhfjkdhgjkdfhgdjkhgjkdgfhjkdfhgjkhfgkhdgjkhgjkdfhgkjdhgkdhgkjdhgkjdhgjkdhgksuifhseiuhfisuhfiushfiushfiuhsfiuhesiufhsuihfiueshfiueshfuihsifuhseiuhfiushfiushfiushfiushfiushfiushfiuhsiufhsiufhsiufhsiuhfsiuhfiushfiushfiuhfsiuhfiuhfsiufhiusfhisuhfiushfiuhfikjdshlijuhsdiughtfuishgiofhgjikdhgiudhiugdehgiueegiueguihgiuehgiuhiueghgiuhegiuheiuhgiuehgiuehgiuehgiuhgiuehgiuehgiuehghuakjfhaifhauifhauifhaiuhfiushfiushifhkkdsjhgdfksjhgkdjshgkjlsdfhgkjdsfhgjkfdhgkjhsdkljfhgkjdfshgkjdshgkjhfdjkhgjkdhgjfkhgdfkgfdsffffffsdkjhfishtiouasghtfuerbghufgueihbgfiughufgthuyhgkjhgfdjkhgjkdfhkjghdjkghdkjhgkjdhgkdhfjkdhgjkdfhgdjkhgjkdgfhjkdfhgjkhfgkhdgjkhgjkdfhgkjdhgkdhgkjdhgkjdhgjkdhgksuifhseiuhfisuhfiushfiushfiuhsfiuhesiufhsuihfiueshfiueshfuihsifuhseiuhfiushfiushfiushfiushfiushfiushfiuhsiufhsiufhsiufhsiuhfsiuhfiushfiushfiuhfsiuhfiuhfsiufhiusfhisuhfiushfiuhfikjdshlijuhsdiughtfuishgiofhgjikdhgiudhiugdehgiueegiueguihgiuehgiuhiueghgiuhegiuheiuhgiuehgiuehgiuehgiuhgiuehgiuehgiuehghuakjfhaifhauifhauifhaiuhfiushfiushifhkkdsjhgdfksjhgkdjshgkjlsdfhgkjdsfhgjkfdhgkjhsdkljfhgkjdfshgkjdshgkjhfdjkhgjkdhgjfkhgdfkgfdsffffffsdkjhfishtiouasghtfuerbghufgueihbgfiughufgthuyhgkjhgfdjkhgjkdfhkjghdjkghdkjhgkjdhgkdhfjkdhgjkdfhgdjkhgjkdgfhjkdfhgjkhfgkhdgjkhgjkdfhgkjdhgkdhgkjdhgkjdhgjkdhgksuifhseiuhfisuhfiushfiushfiuhsfiuhesiufhsuihfiueshfiueshfuihsifuhseiuhfiushfiushfiushfiushfiushfiushfiuhsiufhsiufhsiufhsiuhfsiuhfiushfiushfiuhfsiuhfiuhfsiufhiusfhisuhfiushfiuhfikjdshlijuhsdiughtfuishgiofhgjikdhgiudhiugdehgiueegiueguihgiuehgiuhiueghgiuhegiuheiuhgiuehgiuehgiuehgiuhgiuehgiuehgiuehghuakjfhaifhauifhauifhaiuhfiushfiushifhkkdsjhgdfksjhgkdjshgkjlsdfhgkjdsfhgjkfdhgkjhsdkljfhgkjdfshgkjdshgkjhfdjkhgjkdhgjfkhgdfkgfdsffffffsdkjhfishtiouasghtfuerbghufgueihbgfiughufgthuyhgkjhgfdjkhgjkdfhkjghdjkghdkjhgkjdhgkdhfjkdhgjkdfhgdjkhgjkdgfhjkdfhgjkhfgkhdgjkhgjkdfhgkjdhgkdhgkjdhgkjdhgjkdhgksuifhseiuhfisuhfiushfiushfiuhsfiuhesiufhsuihfiueshfiueshfuihsifuhseiuhfiushfiushfiushfiushfiushfiushfiuhsiufhsiufhsiufhsiuhfsiuhfiushfiushfiuhfsiuhfiuhfsiufhiusfhisuhfiushfiuhfikjdshlijuhsdiughtfuishgiofhgjikdhgiudhiugdehgiueegiueguihgiuehgiuhiueghgiuhegiuheiuhgiuehgiuehgiuehgiuhgiuehgiuehgiuehghuakjfhaifhauifhauifhaiuhfiushfiushifhkkdsjhgdfksjhgkdjshgkjlsdfhgkjdsfhgjkfdhgkjhsdkljfhgkjdfshgkjdshgkjhfdjkhgjkdhgjfkhgdfkgfdsffffffsdkjhfishtiouasghtfuerbghufgueihbgfiughufgthuyhgkjhgfdjkhgjkdfhkjghdjkghdkjhgkjdhgkdhfjkdhgjkdfhgdjkhgjkdgfhjkdfhgjkhfgkhdgjkhgjkdfhgkjdhgkdhgkjdhgkjdhgjkdhgksuifhseiuhfisuhfiushfiushfiuhsfiuhesiufhsuihfiueshfiueshfuihsifuhseiuhfiushfiushfiushfiushfiushfiushfiuhsiufhsiufhsiufhsiuhfsiuhfiushfiushfiuhfsiuhfiuhfsiufhiusfhisuhfiushfiuhfikjdshlijuhsdiughtfuishgiofhgjikdhgiudhiugdehgiueegiueguihgiuehgiuhiueghgiuhegiuheiuhgiuehgiuehgiuehgiuhgiuehgiuehgiuehghuakjfhaifhauifhauifhaiuhfiushfiushifhkkdsjhgdfksjhgkdjshgkjlsdfhgkjdsfhgjkfdhgkjhsdkljfhgkjdfshgkjdshgkjhfdjkhgjkdhgjfkhgdfkgfdsffffffsdkjhfishtiouasghtfuerbghufgueihbgfiughufgthuyhgkjhgfdjkhgjkdfhkjghdjkghdkjhgkjdhgkdhfjkdhgjkdfhgdjkhgjkdgfhjkdfhgjkhfgkhdgjkhgjkdfhgkjdhgkdhgkjdhgkjdhgjkdhgksuifhseiuhfisuhfiushfiushfiuhsfiuhesiufhsuihfiueshfiueshfuihsifuhseiuhfiushfiushfiushfiushfiushfiushfiuhsiufhsiufhsiufhsiuhfsiuhfiushfiushfiuhfsiuhfiuhfsiufhiusfhisuhfiushfiuhfikjdshlijuhsdiughtfuishgiofhgjikdhgiudhiugdehgiueegiueguihgiuehgiuhiueghgiuhegiuheiuhgiuehgiuehgiuehgiuhgiuehgiuehgiuehghuakjfhaifhauifhauifhaiuhfiushfiushifhkkdsjhgdfksjhgkdjshgkjlsdfhgkjdsfhgjkfdhgkjhsdkljfhgkjdfshgkjdshgkjhfdjkhgjkdhgjfkhgdfkgfdsffffffsdkjhfishtiouasghtfuerbghufgueihbgfiughufgthuyhgkjhgfdjkhgjkdfhkjghdjkghdkjhgkjdhgkdhfjkdhgjkdfhgdjkhgjkdgfhjkdfhgjkhfgkhdgjkhgjkdfhgkjdhgkdhgkjdhgkjdhgjkdhgksuifhseiuhfisuhfiushfiushfiuhsfiuhesiufhsuihfiueshfiueshfuihsifuhseiuhfiushfiushfiushfiushfiushfiushfiuhsiufhsiufhsiufhsiuhfsiuhfiushfiushfiuhfsiuhfiuhfsiufhiusfhisuhfiushfiuhfikjdshlijuhsdiughtfuishgiofhgjikdhgiudhiugdehgiueegiueguihgiuehgiuhiueghgiuhegiuheiuhgiuehgiuehgiuehgiuhgiuehgiuehgiuehghuakjfhaifhauifhauifhaiuhfiushfiushifhkkdsjhgdfksjhgkdjshgkjlsdfhgkjdsfhgjkfdhgkjhsdkljfhgkjdfshgkjdshgkjhfdjkhgjkdhgjfkhgdfkgfdsffffffsdkjhfishtiouasghtfuerbghufgueihbgfiughufgthuyhgkjhgfdjkhgjkdfhkjghdjkghdkjhgkjdhgkdhfjkdhgjkdfhgdjkhgjkdgfhjkdfhgjkhfgkhdgjkhgjkdfhgkjdhgkdhgkjdhgkjdhgjkdhgksuifhseiuhfisuhfiushfiushfiuhsfiuhesiufhsuihfiueshfiueshfuihsifuhseiuhfiushfiushfiushfiushfiushfiushfiuhsiufhsiufhsiufhsiuhfsiuhfiushfiushfiuhfsiuhfiuhfsiufhiusfhisuhfiushfiuhfikjdshlijuhsdiughtfuishgiofhgjikdhgiudhiugdehgiueegiueguihgiuehgiuhiueghgiuhegiuheiuhgiuehgiuehgiuehgiuhgiuehgiuehgiuehghuakjfhaifhauifhauifhaiuhfiushfiushifhkkdsjhgdfksjhgkdjshgkjlsdfhgkjdsfhgjkfdhgkjhsdkljfhgkjdfshgkjdshgkjhfdjkhgjkdhgjfkhgdfkgfdsffffffsdkjhfishtiouasghtfuerbghufgueihbgfiughufgthuyhgkjhgfdjkhgjkdfhkjghdjkghdkjhgkjdhgkdhfjkdhgjkdfhgdjkhgjkdgfhjkdfhgjkhfgkhdgjkhgjkdfhgkjdhgkdhgkjdhgkjdhgjkdhgksuifhseiuhfisuhfiushfiushfiuhsfiuhesiufhsuihfiueshfiueshfuihsifuhseiuhfiushfiushfiushfiushfiushfiushfiuhsiufhsiufhsiufhsiuhfsiuhfiushfiushfiuhfsiuhfiuhfsiufhiusfhisuhfiushfiuhfikjdshlijuhsdiughtfuishgiofhgjikdhgiudhiugdehgiueegiueguihgiuehgiuhiueghgiuhegiuheiuhgiuehgiuehgiuehgiuhgiuehgiuehgiuehghufhaiuhfiushfiushifhkkdsjhgdfksjhgkdjshgkjlsdfhgkjdsfhgjkfdhgkjhsdkljfhgkjdfshgkjdshgkjhfdjkhgjkdhgjfkhgdfkgfdsffffffsdkjhfishtiouasghtfuerbghufgueihbgfiughufgthuyhgkjhgfdjkhgjkdfhkjghdjkghdkjhgkjdhgkdhfjkdhgjkdfhgdjkhgjkdgfhjkdfhgjkhfgkhdgjkhgjkdfhgkjdhgkdhgkjdhgkjdhgjkdhgksuifhseiuhfisuhfiushfiushfiuhsfiuhesiufhsuihfiueshfiueshfuihsifuhseiuhfiushfiushfiushfiushfiushfiushfiuhsiufhsiufhsiufhsiuhfsiuhfiushfiushfiuhfsiuhfiuhfsiufhiusfhisuhfiushfiuhfikjdshlijuhsdiughtfuishgiofhgjikdhgiudhiugdehgiueegiueguihgiuehgiuhiueghgiuhegiuheiuhgiuehgiuehgiuehgiuhgiuehgiuehgiuehghu";

        entryOne = new Entry(UUID.randomUUID() ,null,99,desciption,"allowance","", LocalDateTime.now(),LocalDateTime.now());
        assertThrows(EntryValidationException.class,() ->EntryValidator.validateEntry(entryOne));

        entryOne = new Entry(UUID.randomUUID() ,null,99,"desciption","allowance","", LocalDateTime.now(),LocalDateTime.now());
        assertThrows(EntryValidationException.class,() ->EntryValidator.validateEntry(entryOne));

    }

    /**
     * Tests the validation of an entry's amount.
     */
    @Test
    public void validateAmountTest() {
        entryOne = new Entry(UUID.randomUUID() ,null,Float.MAX_VALUE,null,"allowance","", LocalDateTime.now(),LocalDateTime.now());
        assertThrows(EntryValidationException.class,() ->EntryValidator.validateEntry(entryOne));

        entryOne = new Entry(UUID.randomUUID() ,null,Float.MIN_VALUE,"desciption","allowance","", LocalDateTime.now(),LocalDateTime.now());
        assertThrows(EntryValidationException.class,() ->EntryValidator.validateEntry(entryOne));

        entryOne = new Entry(UUID.randomUUID() ,null,1000003.0f,"desciption","allowance","", LocalDateTime.now(),LocalDateTime.now());
        assertThrows(EntryValidationException.class,() ->EntryValidator.validateEntry(entryOne));

    }



}
